# Generated by Django 6.0.6 on 2026-07-18 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='websiteproject',
            index=models.Index(fields=['owner', '-updated_at'], name='builder_web_owner_i_b31905_idx'),
        ),
    ]
