# Generated by Django 6.0.6 on 2026-07-18 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def claim_orphan_projects(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    WebsiteProject = apps.get_model("builder", "WebsiteProject")
    owner = (
        User.objects.filter(is_superuser=True).order_by("id").first()
        or User.objects.filter(is_staff=True).order_by("id").first()
        or User.objects.order_by("id").first()
    )
    if not owner:
        return
    WebsiteProject.objects.filter(owner__isnull=True).update(owner_id=owner.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('studio', 'Studio')], default='free', max_length=20)),
                ('ai_generations_used', models.PositiveIntegerField(default=0)),
                ('ai_period_start', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='websiteproject',
            index=models.Index(fields=['owner', 'deleted_at'], name='builder_web_owner_i_d9b8f8_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(claim_orphan_projects, noop_reverse),
    ]
